vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>')
vim.keymap.set('t', '<Esc><Esc>', '<C-\\><C-n>', { desc = 'Exit terminal mode' })
vim.keymap.set('n', '<C-h>', '<C-w><C-h>', { desc = 'Move focus to the left window' })
vim.keymap.set('n', '<C-l>', '<C-w><C-l>', { desc = 'Move focus to the right window' })
vim.keymap.set('n', '<C-j>', '<C-w><C-j>', { desc = 'Move focus to the lower window' })
vim.keymap.set('n', '<C-k>', '<C-w><C-k>', { desc = 'Move focus to the upper window' })

vim.keymap.set('n', '<C-s>', '<cmd>w<CR>', { desc = 'Save file' })
vim.keymap.set('i', '<C-s>', '<Esc><cmd>w<CR>a', { desc = 'Save file' })
vim.keymap.set('n', '<C-z>', 'u', { desc = 'Undo' })
vim.keymap.set('i', '<C-z>', '<Esc>ua', { desc = 'Undo' })
vim.keymap.set('n', '<C-y>', '<C-r>', { desc = 'Redo' })
vim.keymap.set('i', '<C-y>', '<Esc><C-r>a', { desc = 'Redo' })
vim.keymap.set('v', '<C-c>', '"+y', { desc = 'Copy' })
vim.keymap.set('n', '<C-v>', '"+p', { desc = 'Paste' })
vim.keymap.set('i', '<C-v>', '<C-r>+', { desc = 'Paste' })
vim.keymap.set('v', '<C-x>', '"+d', { desc = 'Cut' })

vim.keymap.set({ 'n', 'i', 'v' }, '<D-p>', function()
  require('fff').find_files()
end, { desc = 'Find files' })
vim.keymap.set({ 'n', 'i', 'v' }, '<D-S-p>', function()
  require('fff').live_grep()
end, { desc = 'Grep workspace' })
vim.keymap.set('n', '<C-p>', function()
  require('fff').find_files()
end, { desc = 'Find files' })
vim.keymap.set('n', '<C-S-p>', function()
  require('fff').live_grep()
end, { desc = 'Grep workspace' })
vim.keymap.set({ 'n', 'i', 'v' }, '<D-S-f>', function()
  require('fff').live_grep()
end, { desc = 'Grep workspace' })
vim.keymap.set({ 'n', 'i', 'v' }, '<D-b>', function()
  require('snacks').explorer()
end, { desc = 'Toggle sidebar' })
vim.keymap.set({ 'n', 'i', 'v' }, '<D-e>', function()
  require('telescope.builtin').buffers()
end, { desc = 'Switch buffer' })
vim.keymap.set({ 'n', 'i' }, '<D-s>', '<Esc><cmd>w<CR>', { desc = 'Save' })
vim.keymap.set({ 'n', 'i' }, '<D-z>', '<Esc>ua', { desc = 'Undo' })
vim.keymap.set({ 'n', 'i' }, '<D-S-z>', '<Esc><C-r>a', { desc = 'Redo' })
vim.keymap.set('v', '<D-c>', '"+y', { desc = 'Copy' })
vim.keymap.set({ 'n', 'i' }, '<D-v>', '<C-r>+', { desc = 'Paste' })
vim.keymap.set('n', '<D-/>', 'gcc', { remap = true, desc = 'Toggle comment' })
vim.keymap.set('v', '<D-/>', 'gc', { remap = true, desc = 'Toggle comment' })
vim.keymap.set({ 'n', 'i' }, '<D-w>', '<cmd>bd<CR>', { desc = 'Close buffer' })
